name: Run Anonymous Apex

on:
  workflow_dispatch:
    inputs:
      apex_script_path:
        description: "Path to Anonymous Apex Script (e.g., scripts/scripts-ci/script.apex)"
        required: true
        type: string
      environment:
        description: "Salesforce Environment"
        required: true
        type: choice
        options:
          - prod
          - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Run Anonymous Apex in ${{ inputs.environment }}
    environment: ${{ inputs.environment }}

    steps:
      - name: 'Setup Node.js'
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 'Checkout Source Code'
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 2

      - name: 'Install Salesforce CLI'
        run: npm install -g @salesforce/cli@2.77.6

      - name: 'Authenticate to Salesforce'
        run: |
          echo "${{ secrets.JWT_SERVER_KEY }}" > server.key
          sf org login jwt \
            --username ${{ secrets.DEPLOYMENT_USER }} \
            --jwt-key-file server.key \
            --client-id ${{ secrets.CONSUMER_KEY }} \
            --instance-url ${{ vars.INSTANCE_URL }} \
            --set-default \
            --set-default-dev-hub

      - name: 'Check if Apex Script Exists'
        run: |
          if [ ! -f "${{ inputs.apex_script_path }}" ]; then
            echo "ERROR: Apex script not found at ${{ inputs.apex_script_path }}";
            exit 1;
          fi

      - name: 'Copy Script to Temporary File and Execute'
        run: |
          cp "${{ inputs.apex_script_path }}" temp_script.apex
          sf apex run --file temp_script.apex --target-org ${{ secrets.DEPLOYMENT_USER }}

  trigger-slack-notification:
    name: Slack Notification
    uses: ./.github/workflows/slack.yml
    with:
      environment: prod
      message: "New changes pushed to the main branch!"
    secrets: inherit
